@startuml
object Author
Author : +AuthorId <int>
Author : +Name <string>
Author : +Email <string>
Author : +Cheeps <List<Cheep>>
Author : +Notifications <List<Notification>>
Author : +Followings <List<Followings>>

object Cheep
Cheep : +CheepId <int>
Cheep : +Text <string>
Cheep : +TimeStamp <DateTime>
Cheep : +AuthorId <int>
Cheep : +Author <Author>

object CheepMention
CheepMention : +Id <int>
CheepMention : +CheepId <int>
CheepMention : +Cheep <Cheep>
CheepMention : +MentionedUsername <string>

object Notification
Notification : +Id <int>
Notification : +AuthorId <int>
Notification : +Content <string>
Notification : +CheepId <int>
Notification : +Cheep <Cheep>
Notification : +TimeStamp <DateTime>

object Following
Following : +Id <int>
Following : +FollowId <int>
Following : +AuthorId <int>

Author "1" --> "0..*" Cheep
Following "0..*" -- "1" Author
CheepMention "0..*" --> "1" Cheep
Notification "0..*" -- "1" Author
Notification "0..*" --> "1" Cheep
@enduml